services:
  library:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    env_file:
      - .env
    volumes:
      - db_volume:$PGDATA

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env
    command:
      celery -A library_core worker -l INFO
    depends_on:
      - redis
  celery-beat:
    build:
      context: .
    env_file:
      - .env
    command:
      celery -A library_core beat -l info
    depends_on:
      - redis
      - celery

volumes:
  db_volume:
