services:
  library:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    env_file:
      - .env
    volumes:
      - db_volume:$PGDATA
volumes:
  db_volume:

